[package]
name = "onca_ral_software"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
onca_core = { path = "../onca_core" }
onca_ral = { path = "../onca_ral" }
